// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0

/*
Package audittools provides a toolkit for establishing a connection to
a RabbitMQ server (with sane defaults) and publishing audit messages in the CADF format to it.
Events are serialized into the subset of CADF that Hermes (https://github.com/sapcc/hermes) can consume.

To use this library, build an Auditor object, then use its Record() function to push events.

# Backing store

Events that cannot be published right away (e.g. while RabbitMQ is unreachable) are put in a backing store,
from which publishing is retried once per minute. By default, the backing store keeps events in memory without limit,
so they are lost when the process exits.

To keep events across restarts, the application can offer more types of backing store in AuditorOpts.BackingStoreFactories.
The operator then selects one through the environment variable "${PREFIX}_BACKING_STORE",
which contains a JSON payload like `{"type":"<type>","params":{...}}`.
For example, an application with a PostgreSQL database could do:

	auditor, err := audittools.NewAuditor(ctx, audittools.AuditorOpts{
		EnvPrefix: "MYSERVICE_AUDIT_RABBITMQ",
		Observer:  observer,
		BackingStoreFactories: map[string]audittools.BackingStoreFactory{
			"sql": audittools.SQLBackingStoreFactoryWithPostgresDB(db),
		},
	})

	# in the environment of the process
	MYSERVICE_AUDIT_RABBITMQ_BACKING_STORE='{"type":"sql"}'

The type "memory" (see NewInMemoryBackingStore) is always available.
Applications that do not use EnvPrefix can build a BackingStore themselves and put it in AuditorOpts.BackingStore.

Besides the memory store, this package provides two types of backing store.
SQLBackingStoreFactoryWithPostgresDB is the right choice for applications that already have a PostgreSQL database.
NewFileBackingStore keeps events in files, and is only useful if each replica has its own persistent volume,
because files on the container filesystem are lost when the pod is replaced.

If the backing store is full or cannot be written to, no further events are taken until that event can be published or stored,
so Record() blocks once its small buffer has filled up.
Events that Record() has accepted, but that were neither published nor written to the backing store yet
(at most 21: the 20 events in its buffer and the one being processed) only exist in memory,
so they are lost when the process exits, even with a durable backing store.
Events from the backing store may be published out of order, and may be published twice
if the process exits after publishing them, but before removing them from the backing store,
or if removing them from the backing store fails.

# SQL backing store

The SQL backing store keeps events in a table like the one below.
The application must create this table, e.g. in its schema migrations (see pgruntime.ConnectionBehavior).
On startup, the SQL backing store only checks that the table exists.

	CREATE TABLE audit_events (
		id         BIGSERIAL NOT NULL PRIMARY KEY,
		event_data JSONB     NOT NULL
	);

Several processes can share one table, e.g. multiple replicas of the same API.
Each stored event is then published by only one of them.
But processes that publish to different RabbitMQ queues must use different tables,
because the table does not record which queue an event belongs to.
The gauge "audittools_backing_store_events" counts all events in the table,
so every process that shares the table reports the same value.
*/
package audittools

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"net"
	"net/url"
	"slices"
	"strconv"
	"strings"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/sapcc/go-api-declarations/cadf"
	"go.xyrillian.de/gg/assert"
	"go.xyrillian.de/gg/jsonmatch"

	"github.com/sapcc/go-bits/internal"
	"github.com/sapcc/go-bits/logg"
	"github.com/sapcc/go-bits/osext"
)

// Auditor is a high-level interface for audit event acceptors.
// In a real process, use NewAuditor() or NewNullAuditor() depending on whether you have RabbitMQ client credentials.
// In a test scenario, use NewMockAuditor() to get an assertable mock implementation.
type Auditor interface {
	Record(Event)
}

////////////////////////////////////////////////////////////////////////////////
// type standardAuditor

// AuditorOpts contains options for NewAuditor().
type AuditorOpts struct {
	// Required. Identifies the current process within the events sent by it.
	// The Observer.ID field should be set to a UUID, such as those generated by GenerateUUID().
	Observer Observer

	// Optional. If given, RabbitMQ connection options will be read from the following environment variables:
	//   - "${PREFIX}_HOSTNAME" (defaults to "localhost")
	//   - "${PREFIX}_PORT" (defaults to "5672")
	//   - "${PREFIX}_USERNAME" (defaults to "guest")
	//   - "${PREFIX}_PASSWORD" (defaults to "guest")
	//   - "${PREFIX}_QUEUE_NAME" (required)
	//   - "${PREFIX}_BACKING_STORE" (defaults to `{"type":"memory"}`, see "Backing store" in the package documentation)
	EnvPrefix string

	// Required if EnvPrefix is empty, ignored otherwise.
	// Contains the RabbitMQ connection options that would otherwise be read from environment variables.
	ConnectionURL string
	QueueName     string

	// Optional. If given, the Auditor will register its Prometheus metrics with this registry instead of the default registry.
	// The following metrics are registered:
	//   - "audittools_successful_submissions" (counter, no labels)
	//   - "audittools_failed_submissions" (counter, no labels)
	// The backing stores in this package also register these metrics with this registry:
	//   - "audittools_backing_store_writes_total" (counter, no labels)
	//   - "audittools_backing_store_reads_total" (counter, no labels)
	//   - "audittools_backing_store_errors_total" (counter, label "operation")
	//   - "audittools_backing_store_events" (gauge, no labels; memory and SQL backing stores only)
	//   - "audittools_backing_store_size_bytes" and "audittools_backing_store_files" (gauges, no labels; file backing store only)
	Registry prometheus.Registerer

	// Optional. If given, events that cannot be published right away are put in this BackingStore.
	// Otherwise, the backing store is chosen through "${PREFIX}_BACKING_STORE" (see "Backing store" in the package documentation).
	BackingStore BackingStore

	// Optional. More types of backing store that can be chosen through "${PREFIX}_BACKING_STORE", keyed by type name.
	// The type "memory" (NewInMemoryBackingStore) is always available.
	BackingStoreFactories map[string]BackingStoreFactory
}

func (opts AuditorOpts) getConnectionOptions() (rabbitURL url.URL, queueName string, err error) {
	// option 1: passed explicitly
	if opts.EnvPrefix == "" {
		if opts.ConnectionURL == "" {
			return url.URL{}, "", errors.New("missing required value: AuditorOpts.ConnectionURL")
		}
		if opts.QueueName == "" {
			return url.URL{}, "", errors.New("missing required value: AuditorOpts.QueueName")
		}
		rabbitURL, err := url.Parse(opts.ConnectionURL)
		if err != nil {
			return url.URL{}, "", fmt.Errorf("while parsing AuditorOpts.ConnectionURL (%q): %w", opts.ConnectionURL, err)
		}
		return *rabbitURL, opts.QueueName, nil
	}

	// option 2: passed via environment variables
	queueName, err = osext.NeedGetenv(opts.EnvPrefix + "_QUEUE_NAME")
	if err != nil {
		return url.URL{}, "", err
	}
	hostname := osext.GetenvOrDefault(opts.EnvPrefix+"_HOSTNAME", "localhost")
	port, err := strconv.Atoi(osext.GetenvOrDefault(opts.EnvPrefix+"_PORT", "5672"))
	if err != nil {
		return url.URL{}, "", fmt.Errorf("invalid value for %s_PORT: %w", opts.EnvPrefix, err)
	}
	username := osext.GetenvOrDefault(opts.EnvPrefix+"_USERNAME", "guest")
	pass := osext.GetenvOrDefault(opts.EnvPrefix+"_PASSWORD", "guest")
	rabbitURL = url.URL{
		Scheme: "amqp",
		Host:   net.JoinHostPort(hostname, strconv.Itoa(port)),
		User:   url.UserPassword(username, pass),
		Path:   "/",
	}
	return rabbitURL, queueName, nil
}

type standardAuditor struct {
	Observer  Observer
	EventSink chan<- cadf.Event
}

// NewAuditor builds an Auditor connected to a RabbitMQ instance, using the provided configuration.
func NewAuditor(ctx context.Context, opts AuditorOpts) (Auditor, error) {
	// validate provided options (EnvPrefix, ConnectionURL and QueueName are checked later in getConnectionOptions())
	if opts.Observer.TypeURI == "" {
		return nil, errors.New("missing required value: AuditorOpts.Observer.TypeURI")
	}
	if opts.Observer.Name == "" {
		return nil, errors.New("missing required value: AuditorOpts.Observer.Name")
	}
	if opts.Observer.ID == "" {
		return nil, errors.New("missing required value: AuditorOpts.Observer.ID")
	}

	// register Prometheus metrics
	successCounter := prometheus.NewCounter(prometheus.CounterOpts{
		Name: "audittools_successful_submissions",
		Help: "Counter for successful audit event submissions to the Hermes RabbitMQ server.",
	})
	failureCounter := prometheus.NewCounter(prometheus.CounterOpts{
		Name: "audittools_failed_submissions",
		Help: "Counter for failed (but retryable) audit event submissions to the Hermes RabbitMQ server.",
	})
	successCounter.Add(0)
	failureCounter.Add(0)
	if opts.Registry == nil {
		prometheus.MustRegister(successCounter)
		prometheus.MustRegister(failureCounter)
	} else {
		opts.Registry.MustRegister(successCounter)
		opts.Registry.MustRegister(failureCounter)
	}

	// spawn event delivery goroutine
	rabbitURL, queueName, err := opts.getConnectionOptions()
	if err != nil {
		return nil, err
	}
	backingStore := opts.BackingStore
	if backingStore == nil {
		backingStore, err = opts.newBackingStoreFromEnv()
		if err != nil {
			return nil, err
		}
	}
	eventChan := make(chan cadf.Event, 20)
	go auditTrail{
		EventSink:           eventChan,
		OnSuccessfulPublish: func() { successCounter.Inc() },
		OnFailedPublish:     func() { failureCounter.Inc() },
		BackingStore:        backingStore,
	}.Commit(ctx, rabbitURL, queueName)

	return &standardAuditor{
		Observer:  opts.Observer,
		EventSink: eventChan,
	}, nil
}

func (opts AuditorOpts) newBackingStoreFromEnv() (BackingStore, error) {
	configJSON := `{"type":"memory"}`
	if opts.EnvPrefix != "" {
		configJSON = osext.GetenvOrDefault(opts.EnvPrefix+"_BACKING_STORE", configJSON)
	}
	var cfg struct {
		Type   string          `json:"type"`
		Params json.RawMessage `json:"params"`
	}
	err := unmarshalJSONStrict([]byte(configJSON), &cfg)
	if err != nil {
		return nil, fmt.Errorf("invalid value for %s_BACKING_STORE: %w", opts.EnvPrefix, err)
	}
	if len(cfg.Params) == 0 {
		cfg.Params = json.RawMessage(`{}`)
	}

	factories := map[string]BackingStoreFactory{"memory": NewInMemoryBackingStore}
	maps.Copy(factories, opts.BackingStoreFactories)
	factory, ok := factories[cfg.Type]
	if !ok {
		return nil, fmt.Errorf("invalid value for %s_BACKING_STORE: unknown backing store type %q (available: %s)",
			opts.EnvPrefix, cfg.Type, strings.Join(slices.Sorted(maps.Keys(factories)), ", "))
	}
	return factory(cfg.Params, opts)
}

// Record implements the Auditor interface.
func (a *standardAuditor) Record(event Event) {
	a.EventSink <- event.ToCADF(a.Observer.ToCADF())
}

////////////////////////////////////////////////////////////////////////////////
// type nullAuditor

// NewNullAuditor returns an Auditor that does nothing (except produce a debug log of the discarded event).
// This is only intended to be used for non-productive deployments without a Hermes instance.
func NewNullAuditor() Auditor {
	return nullAuditor{}
}

type nullAuditor struct{}

// Record implements the Auditor interface.
func (nullAuditor) Record(event Event) {
	if logg.ShowDebug {
		msg, err := json.Marshal(event.ToCADF(cadf.Resource{}))
		if err == nil {
			logg.Debug("audit event received: %s", string(msg))
		}
	}
}

////////////////////////////////////////////////////////////////////////////////
// type MockAuditor

// MockAuditor is a test double that satisfies the Auditor interface.
// It stores events sent to it and provides test assertions on those events.
type MockAuditor struct {
	events []cadf.Event
}

// NewMockAuditor constructs a new MockAuditor instance.
func NewMockAuditor() *MockAuditor {
	return &MockAuditor{}
}

// Record implements the Auditor interface.
func (a *MockAuditor) Record(event Event) {
	eventAsCADF := event.ToCADF(cadf.Resource{})
	a.events = append(a.events, a.normalize(eventAsCADF))
}

// ExpectEvents checks that the recorded events are equivalent to the supplied expectation.
// At the end of the call, the recording will be disposed, so the next ExpectEvents call will not check against the same events again.
//
// If you do not have a *testing.T (e.g. under Ginkgo), use func RecordedEvents instead.
func (a *MockAuditor) ExpectEvents(t assert.TestingTB, expectedEvents ...cadf.Event) {
	t.Helper()

	actualEvents := a.RecordedEvents()

	if len(expectedEvents) == 0 {
		if len(actualEvents) == 0 {
			return
		}
	} else {
		for idx, event := range expectedEvents {
			expectedEvents[idx] = a.normalize(event)
		}
	}

	// normalize nil to [] for better jsonmatch.Diff output
	if len(actualEvents) == 0 {
		actualEvents = []cadf.Event{}
	}
	if len(expectedEvents) == 0 {
		expectedEvents = []cadf.Event{}
	}

	actualBuf, err := json.Marshal(map[string]any{"events": actualEvents})
	if err != nil {
		t.Errorf("cannot marshal recorded events to JSON: %s", err.Error())
		return
	}
	expectedBuf, err := json.Marshal(map[string]any{"events": expectedEvents})
	if err != nil {
		t.Errorf("cannot marshal expected events to JSON: %s", err.Error())
		return
	}

	var expected jsonmatch.Object
	err = json.Unmarshal(expectedBuf, &expected)
	if err != nil {
		t.Errorf("cannot unmarshal expected events from JSON: %s", err.Error())
		return
	}

	// attach a custom Diffable to `events[_].target.attachments[_].content` to allow jsonmatch
	// to recurse into JSON payloads within JSON strings and generate better output
	if events, ok := expected["events"].([]any); ok {
		for _, e := range events {
			if event, ok := e.(map[string]any); ok {
				if target, ok := event["target"].(map[string]any); ok {
					if attachments, ok := target["attachments"].([]any); ok {
						for _, a := range attachments {
							if attachment, ok := a.(map[string]any); ok {
								if typeURI, ok := attachment["typeURI"].(string); ok && typeURI == "mime:application/json" {
									if content, ok := attachment["content"].(string); ok {
										attachment["content"] = tryNewJSONWithinJSONString(content)
									}
								}
							}
						}
					}
				}
			}
		}
	}

	for _, d := range expected.DiffAgainst(actualBuf) {
		t.Errorf("%s", d.String())
	}
}

// jsonWithinJSONString is a custom [jsonmatch.Diffable] that expects a JSON string whose contents match the provided Diffable.
type jsonWithinJSONString struct {
	inner jsonmatch.Diffable
}

// tryNewJSONWithinJSONString takes a value from `events[_].target.attachments[_].content`
// and tries to cast it into a structured jsonmatch.Diffable.
//
// This is only done for content payloads that look like they benefit from being structured, not for scalar values
// (e.g. there is not much advantage in converting `"true"` into `jsonWithinJSONString{jsonmatch.Scalar(true)}`).
func tryNewJSONWithinJSONString(content string) any {
	trimmed := strings.TrimSpace(content)
	switch {
	case strings.HasPrefix(trimmed, "{"):
		var object jsonmatch.Object
		err := json.Unmarshal([]byte(content), &object)
		if err != nil {
			return content
		}
		return jsonWithinJSONString{object}
	case strings.HasPrefix(trimmed, "["):
		var array jsonmatch.Array
		err := json.Unmarshal([]byte(content), &array)
		if err != nil {
			return content
		}
		return jsonWithinJSONString{array}
	default:
		return content
	}
}

// DiffAgainst implements the [jsonmatch.Diffable] interface.
func (j jsonWithinJSONString) DiffAgainst(buf []byte) []jsonmatch.Diff {
	var payload string
	err := json.Unmarshal(buf, &payload)
	if err != nil {
		d := jsonmatch.Diff{
			Kind:       fmt.Sprintf("unmarshal error (%s)", err.Error()),
			Pointer:    "",
			ActualJSON: strings.ToValidUTF8(string(buf), "\uFFFD"),
		}
		buf, err := json.Marshal(j.inner)
		if err == nil {
			d.ExpectedJSON = string(buf)
		} else {
			d.ExpectedJSON = fmt.Sprintf("<not marshalable to JSON, %%#v is %#v>", j.inner)
		}
		return []jsonmatch.Diff{d}
	}
	return j.inner.DiffAgainst([]byte(payload))
}

// MarshalJSON implements the [json.Marshaler] interface.
// This implementation is meant to allow package jsonmatch to render better diffs.
func (j jsonWithinJSONString) MarshalJSON() ([]byte, error) {
	return json.Marshal(j.inner)
}

// RecordedEvents returns the list of recorded events.
// At the end of the call, the recording will be disposed, so the next RecordedEvents call will not see the same events again.
//
// This is intended for use with test assertion libraries where ExpectEvents does not work
// For Ginkgo/Gomega specifically, we recommend matching the event payloads with the gstruct submodule of gomega.
func (a *MockAuditor) RecordedEvents() []cadf.Event {
	result := a.events
	a.events = nil
	return result
}

// IgnoreEventsUntilNow clears the list of recorded events, so that the next
// ExpectEvents() or RecordedEvents() will only cover events generated after this point.
func (a *MockAuditor) IgnoreEventsUntilNow() {
	a.events = nil
}

func (a *MockAuditor) normalize(event cadf.Event) cadf.Event {
	// overwrite some attributes where we don't care about variance
	event.TypeURI = "http://schemas.dmtf.org/cloud/audit/1.0/event"
	event.ID = "00000000-0000-0000-0000-000000000000"
	event.EventTime = "2006-01-02T15:04:05.999999+00:00"
	event.EventType = "activity"
	if event.Initiator.TypeURI == internal.StandardUserInfoTypeURI {
		// we do not care about the Initiator unless it's a non-standard UserInfo
		event.Initiator = cadf.Resource{}
	}
	event.Observer = cadf.Resource{}
	return event
}
